version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}        
      MYSQL_DATABASE: ${MYSQL_DATABASE}             
      MYSQL_USER: ${MYSQL_USER}                      
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}       
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      etl-network:
        ipv4_address: 172.100.0.2
    
  minio:
    image: quay.io/minio/minio
    container_name: object-storage
    volumes:
      - ./minio/data/:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9090'
    command: minio server /data --console-address ":9090"
    networks:
      etl-network:
        ipv4_address: 172.100.0.3

volumes:
  mysql_data:

networks:
  etl-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
    name: etl-network
